version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          spec: cypress/integration/addtodo_spec.js
          post-steps:
            - store_artifacts:
                path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots
